language: julia
os:
    - linux
    - osx
julia:
    - 0.6
notifications:
    email: false
git:
    depth: 99999999
after_success:
    - >-
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
          julia -e 'Pkg.add("Documenter")';
          julia -e 'cd(Pkg.dir("UnitfulAstro")); include(joinpath("docs", "make.jl"))';
      fi
