language: julia
os:
    - linux
    - osx
julia:
    - 0.6
    - nightly
notifications:
    email: false
git:
    depth: 99999999
allow_failures:
    - julia: nightly
after_success:
    - >-
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_JULIA_VERSION" == "0.6" ]];
            julia -e 'Pkg.add("Documenter")';
            julia -e 'cd(Pkg.dir("UnitfulAstro")); include(joinpath("docs", "make.jl"))'
        fi
